# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Auth', '~> 5.3.0'

target 'reactnativephoneauthexample' do

end
